"""
TestCopilotGame - Settings and Constants
All game configuration values and constants.
"""

# Screen settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
GAME_TITLE = "Space Shooter - TestCopilotGame"

# Colors
BG_COLOR = (10, 10, 30)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 100, 255)
YELLOW = (255, 255, 0)
CYAN = (0, 255, 255)
MAGENTA = (255, 0, 255)
ORANGE = (255, 165, 0)
PURPLE = (128, 0, 128)
DARK_GRAY = (40, 40, 40)
LIGHT_GRAY = (200, 200, 200)
GOLD = (255, 215, 0)
SILVER = (192, 192, 192)

# Player settings
PLAYER_SPEED = 400
PLAYER_HEALTH = 100
PLAYER_SIZE = (60, 60)
PLAYER_COLOR = CYAN
PLAYER_INVULNERABILITY_TIME = 2.0
PLAYER_BLINK_INTERVAL = 0.1

# Bullet settings
BULLET_SPEED = 600
BULLET_SIZE = (8, 20)
BULLET_COLOR = YELLOW
BULLET_DAMAGE = 10
BULLET_COOLDOWN = 0.15

# Enemy bullet settings
ENEMY_BULLET_SPEED = 300
ENEMY_BULLET_SIZE = (6, 15)
ENEMY_BULLET_COLOR = RED
ENEMY_BULLET_DAMAGE = 10
ENEMY_BULLET_COOLDOWN = 1.0

# Power-up settings
POWERUP_SPAWN_CHANCE = 0.15
POWERUP_SIZE = (30, 30)
POWERUP_SPEED = 100
POWERUP_DURATION = 10.0

# Health power-up
HEALTH_POWERUP_HEAL = 25
HEALTH_POWERUP_COLOR = GREEN

# Speed power-up
SPEED_POWERUP_MULTIPLIER = 1.5
SPEED_POWERUP_COLOR = CYAN

# Damage power-up
DAMAGE_POWERUP_MULTIPLIER = 2.0
DAMAGE_POWERUP_COLOR = RED

# Shield power-up
SHIELD_POWERUP_DURATION = 15.0
SHIELD_POWERUP_COLOR = BLUE

# Rapid fire power-up
RAPID_FIRE_COOLDOWN = 0.05
RAPID_FIRE_COLOR = YELLOW

# Multi-shot power-up
MULTI_SHOT_COUNT = 3
MULTI_SHOT_ANGLE = 15
MULTI_SHOT_COLOR = MAGENTA

# Enemy settings
ENEMY_SPAWN_RATE = 2.0
ENEMY_COUNT_PER_WAVE = 5
ENEMY_BASE_HEALTH = 20
ENEMY_SPEED_MIN = 50
ENEMY_SPEED_MAX = 150
ENEMY_SIZE = (40, 40)
ENEMY_COLOR = RED
ENEMY_SCORE_BASE = 10

# Enemy types
ENEMY_TYPE_BASIC = 'basic'
ENEMY_TYPE_FAST = 'fast'
ENEMY_TYPE_TANK = 'tank'
ENEMY_TYPE_SHOOTER = 'shooter'
ENEMY_TYPE_KAMIKAZE = 'kamikaze'
ENEMY_TYPE_SWARM = 'swarm'
ENEMY_TYPE_ELITE = 'elite'
ENEMY_TYPE_BOSS = 'boss'

# Fast enemy
FAST_ENEMY_HEALTH = 10
FAST_ENEMY_SPEED = 250
FAST_ENEMY_SCORE = 15

# Tank enemy
TANK_ENEMY_HEALTH = 100
TANK_ENEMY_SPEED = 30
TANK_ENEMY_SCORE = 50

# Shooter enemy
SHOOTER_ENEMY_HEALTH = 30
SHOOTER_ENEMY_SPEED = 80
SHOOTER_ENEMY_SCORE = 25
SHOOTER_ENEMY_FIRE_RATE = 2.0

# Kamikaze enemy
KAMIKAZE_ENEMY_HEALTH = 15
KAMIKAZE_ENEMY_SPEED = 300
KAMIKAZE_ENEMY_SCORE = 20
KAMIKAZE_EXPLOSION_DAMAGE = 50
KAMIKAZE_EXPLOSION_RADIUS = 80

# Swarm enemy
SWARM_ENEMY_HEALTH = 5
SWARM_ENEMY_SPEED = 200
SWARM_ENEMY_SCORE = 5

# Elite enemy
ELITE_ENEMY_HEALTH = 80
ELITE_ENEMY_SPEED = 120
ELITE_ENEMY_SCORE = 100
ELITE_ENEMY_FIRE_RATE = 1.5

# Boss settings
BOSS_SPAWN_LEVEL = 5
BOSS_HEALTH_MULTIPLIER = 10
BOSS_SPEED = 80
BOSS_SIZE = (120, 120)
BOSS_COLOR = PURPLE
BOSS_DAMAGE = 20
BOSS_SCORE = 1000

# Boss types
BOSS_TYPE_BASIC = 'basic_boss'
BOSS_TYPE_TWIN = 'twin_boss'
BOSS_TYPE_MEGA = 'mega_boss'
BOSS_TYPE_FINAL = 'final_boss'

# Boss attack patterns
BOSS_ATTACK_SINGLE = 'single'
BOSS_ATTACK_SPREAD = 'spread'
BOSS_ATTACK_SPIRAL = 'spiral'
BOSS_ATTACK_WAVE = 'wave'
BOSS_ATTACK_HOMING = 'homing'

# Particle settings
PARTICLE_COUNT = 50
PARTICLE_LIFETIME = 1.0
PARTICLE_SPEED_MIN = 50
PARTICLE_SPEED_MAX = 200
EXPLOSION_PARTICLE_COUNT = 30
EXPLOSION_COLOR = ORANGE

# Background settings
STAR_COUNT = 200
STAR_SPEED_MIN = 50
STAR_SPEED_MAX = 300
STAR_COLOR = WHITE
PARALLAX_LAYERS = 3

# Level settings
LEVEL_ENEMY_COUNT_MULTIPLIER = 1.2
LEVEL_ENEMY_HEALTH_MULTIPLIER = 1.1
LEVEL_ENEMY_SPEED_MULTIPLIER = 1.05
LEVEL_ENEMY_SPAWN_RATE_MULTIPLIER = 0.95
LEVEL_COMPLETE_BONUS = 500
BOSS_DEFEAT_BONUS = 5000

# Game settings
STARTING_LIVES = 3
MAX_LIVES = 5
SCORE_MULTIPLIER = 1.0

# UI settings
FONT_SIZE_LARGE = 72
FONT_SIZE_MEDIUM = 48
FONT_SIZE_SMALL = 24
FONT_SIZE_TINY = 18
HUD_MARGIN = 20
BUTTON_WIDTH = 300
BUTTON_HEIGHT = 60
BUTTON_SPACING = 20

# Animation settings
ANIMATION_FPS = 10
BLINK_DURATION = 0.2

# Sound settings
SOUND_ENABLED = True
MUSIC_ENABLED = True
MUSIC_VOLUME = 0.5
SFX_VOLUME = 0.7

# Save system
SAVE_FILE = 'scores.json'
MAX_HIGH_SCORES = 10

# Debug settings
DEBUG = False
SHOW_HITBOXES = False
SHOW_FPS = True

# Collision settings
COLLISION_DAMAGE_MULTIPLIER = 1.0

# Screen shake settings
SCREEN_SHAKE_DURATION = 0.3
SCREEN_SHAKE_INTENSITY = 10

# Power-up rarity
POWERUP_RARITY_COMMON = 0.5
POWERUP_RARITY_RARE = 0.3
POWERUP_RARITY_EPIC = 0.15
POWERUP_RARITY_LEGENDARY = 0.05

# Weapon upgrade levels
WEAPON_LEVEL_MAX = 5
WEAPON_UPGRADE_DAMAGE_INCREASE = 1.2
WEAPON_UPGRADE_FIRE_RATE_INCREASE = 0.9

# Special effects
METEOR_SPAWN_RATE = 0.001
METEOR_SPEED = 400
METEOR_SIZE = (60, 60)
METEOR_DAMAGE = 100

# Achievement system (placeholder)
ACHIEVEMENT_KILL_100 = {'name': 'Hunter', 'desc': 'Kill 100 enemies'}
ACHIEVEMENT_KILL_1000 = {'name': 'Slayer', 'desc': 'Kill 1000 enemies'}
ACHIEVEMENT_REACH_LEVEL_10 = {'name': 'Veteran', 'desc': 'Reach level 10'}
ACHIEVEMENT_REACH_LEVEL_20 = {'name': 'Master', 'desc': 'Reach level 20'}
ACHIEVEMENT_DEFEAT_BOSS = {'name': 'Boss Killer', 'desc': 'Defeat a boss'}
ACHIEVEMENT_NO_DAMAGE = {'name': 'Untouchable', 'desc': 'Complete a level without taking damage'}
ACHIEVEMENT_HIGH_SCORE = {'name': 'High Flyer', 'desc': 'Reach 100,000 points'}

# Game balance tuning
DIFFICULTY_CURVE = 1.1
ENEMY_SPAWN_INCREASE_PER_LEVEL = 2
BOSS_HEALTH_INCREASE_PER_LEVEL = 1.5

# Input settings
CONTROL_SCHEME_ARROWS = 'arrows'
CONTROL_SCHEME_WASD = 'wasd'
DEFAULT_CONTROL_SCHEME = CONTROL_SCHEME_WASD

# Camera settings
CAMERA_SMOOTHING = 0.1
CAMERA_FOLLOW_PLAYER = True

# Performance settings
MAX_PARTICLES = 1000
MAX_BULLETS = 500
MAX_ENEMIES = 100
PARTICLE_CULLING_DISTANCE = 100

# Advanced gameplay settings
COMBAT_COMBO_WINDOW = 5.0  # Seconds to maintain combo
COMBO_MULTIPLIER_MAX = 3.0  # Maximum combo multiplier
COMBO_SCORE_BONUS = 0.1  # Score bonus per combo hit
COMBO_TIMER_RESET = 0.5  # Time before combo resets

# Weapon upgrade system
WEAPON_UPGRADE_COST_BASE = 1000
WEAPON_UPGRADE_COST_MULTIPLIER = 1.5
WEAPON_MAX_LEVEL = 10
WEAPON_UPGRADE_DAMAGE_STEP = 1.2
WEAPON_UPGRADE_FIRE_RATE_STEP = 0.9
WEAPON_UPGRADE_SPREAD_REDUCTION = 0.05

# Shield system
SHIELD_RECHARGE_RATE = 1.0  # Health per second
SHIELD_RECHARGE_DELAY = 5.0  # Seconds before recharge starts
SHIELD_MAX_OVERCHARGE = 1.5  # Can overcharge to 150% of max

# Energy system (for special abilities)
ENERGY_MAX = 100
ENERGY_RECHARGE_RATE = 10.0  # Energy per second
ENERGY_SPECIAL_COST = 50  # Energy cost for special ability
ENERGY_ULTIMATE_COST = 100  # Energy cost for ultimate ability

# Difficulty scaling
DIFFICULTY_EASY = 0.7
DIFFICULTY_NORMAL = 1.0
DIFFICULTY_HARD = 1.5
DIFFICULTY_INSANE = 2.0
CURRENT_DIFFICULTY = DIFFICULTY_NORMAL

# Screen effects
SCREEN_FLASH_DURATION = 0.2
SCREEN_FLASH_COLOR = WHITE
SCREEN_FLASH_ALPHA = 128
CAMERA_ZOOM_MIN = 0.8
CAMERA_ZOOM_MAX = 1.2
CAMERA_ZOOM_SPEED = 2.0

# Advanced enemy AI
ENEMY_AGGRESSION_MULTIPLIER = 1.0
ENEMY_FORMATION_MODE = False
ENEMY_FORMATION_SIZE = 5
ENEMY_SWARM_BEHAVIOR = True
ENEMY_RETREAT_THRESHOLD = 0.3  # Health percentage before retreat

# Networking (placeholder for future multiplayer)
NETWORK_ENABLED = False
NETWORK_PORT = 7777
NETWORK_MAX_PLAYERS = 4
NETWORK_SYNC_RATE = 30  # Updates per second

# Cheat codes (for testing/debugging)
CHEAT_GOD_MODE = False
CHEAT_INFINITE_AMMO = False
CHEAT_MAX_WEAPON = False
CHEAT_INVINCIBLE = False
CHEAT_ONE_SHOT_KILL = False

# Statistics tracking
STATS_ENEMIES_KILLED = 0
STATS_BULLETS_FIRED = 0
STATS_POWERUPS_COLLECTED = 0
STATS_BOSSES_DEFEATED = 0
STATS_TOTAL_PLAY_TIME = 0.0
STATS_LEVELS_COMPLETED = 0
STATS_DEATHS = 0
STATS_DAMAGE_DEALT = 0
STATS_DAMAGE_TAKEN = 0

# Modding support (future feature)
MODS_ENABLED = False
MODS_DIRECTORY = "mods"
MODS_AUTO_LOAD = False

# Localization
LANGUAGE = "en"
LOCALIZATION_ENABLED = False
LOCALIZATION_DIRECTORY = "locales"

# Analytics (optional, for future implementation)
ANALYTICS_ENABLED = False
ANALYTICS_ENDPOINT = ""
ANALYTICS_KEY = ""

# Quality of life features
AUTO_PAUSE_ON_FOCUS_LOSS = True
SHOW_DAMAGE_NUMBERS = True
DAMAGE_NUMBER_DURATION = 1.0
DAMAGE_NUMBER_SPEED = 100.0
COMBAT_TEXT_ENABLED = True
MINIMAP_ENABLED = False
MINIMAP_SIZE = 200
MINIMAP_POSITION = (SCREEN_WIDTH - 220, 20)

# Advanced graphics options
VSYNC_ENABLED = True
ANTI_ALIASING_ENABLED = False
PARTICLE_QUALITY = 1.0  # 0.0 to 1.0
LIGHTING_ENABLED = False
BLOOM_ENABLED = False
MOTION_BLUR_ENABLED = False

# Audio options
DYNAMIC_MUSIC = True
MUSIC_TRANSITION_TIME = 2.0
AMBIENT_SOUNDS_ENABLED = True
VOICE_OVER_ENABLED = False
SFX_VOLUME_MASTER = 1.0
SFX_VOLUME_EXPLOSIONS = 1.0
SFX_VOLUME_WEAPONS = 1.0
SFX_VOLUME_AMBIENT = 0.5

# Control customization
CONTROLS_CUSTOMIZABLE = True
CONTROLS_INPUT_BUFFER = 0.1  # Input buffer window in seconds
CONTROLS_REPEAT_DELAY = 0.3  # Delay before key repeat starts
CONTROLS_REPEAT_RATE = 0.05  # Key repeat rate

# Save system options
AUTO_SAVE_ENABLED = True
AUTO_SAVE_INTERVAL = 60.0  # Seconds between auto-saves
SAVE_FILE_BACKUP_COUNT = 3
CLOUD_SAVE_ENABLED = False

# Development tools
DEV_MODE = DEBUG
DEV_SHOW_COLLIDERS = False
DEV_SHOW_SPAWN_POINTS = False
DEV_SHOW_AI_PATHS = False
DEV_INVINCIBLE_PLAYER = False
DEV_SHOW_PERFORMANCE = True
DEV_CONSOLE_ENABLED = False

# Testing and debugging
UNIT_TESTS_ENABLED = False
INTEGRATION_TESTS_ENABLED = False
PERFORMANCE_PROFILING = False
MEMORY_LEAK_DETECTION = False

# Final initialization
if DEBUG:
    print("Settings loaded successfully")
    print(f"Screen resolution: {SCREEN_WIDTH}x{SCREEN_HEIGHT}")
    print(f"FPS target: {FPS}")
    print(f"Difficulty: {CURRENT_DIFFICULTY}")

